[package]
name = "thresh"
version = "0.1.0"
description = "Thresh - Cardano Wallet"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "thresh_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.9.5"
tokio = { version = "1", features = ["rt", "macros"] }
lazy_static = "1.4"
pallas-addresses = "0.33.0"
pallas-crypto = "0.33.0"
cardano-multiplatform-lib = "6.2.0"
bech32 = "0.11.0"
bip39 = "2.2.0"
ed25519-bip32 = "0.4.1"
ed25519-dalek = "2.1.0"
cryptoxide = "0.5.1"
rand = "0.8.5"
dirs = "5.0.1"
hex = "0.4.3"
utxorpc = "0.11.0"
pallas-primitives = "0.33.0"
pallas-codec = "0.33.0"
pallas-txbuilder = "0.33.0"

[dev-dependencies]
tempfile = "3.8.1"

